#!/usr/bin/env node

/**
 * OpenClaw Native wrapper for ClawCommit decision cycle.
 *
 * This wrapper is intentionally thin: it shells out to the repo-canonical
 * decision_cycle.sh and supports either explicit prompt/output args or
 * a prebuilt decision JSON file generated by convert-to-clawcommit.js.
 */

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

function usage() {
  console.log(`Usage:
  node integrations/openclaw/openclaw.js --repo . --network bscTestnet --contract <ADDR>
    [--rpc <RPC_URL>] [--allow-mainnet-writes <true|false>]
    [--decision-json <PATH>]
    [--prompt "<PROMPT>" --output "<OUTPUT>" --model-version "<MODEL_VERSION>" --nonce "0x..."]
    [--json-out <PATH>] [--json-include-prompt]
    [--links-out <PATH>] [--links-title <TITLE>]
    [--links-include-prompt] [--links-prompt-max-chars <N>] [--links-no-redact]
    [--post-gh-pr <PR_NUMBER>] [--gh-repo <owner/repo>]

Examples:
  npm run openclaw:attest --
    --repo .
    --network bscTestnet
    --contract "$CLAWCOMMIT_CONTRACT_TESTNET"
    --decision-json .clawcommit/decision.json
    --json-out .clawcommit/pr-1.json
    --json-include-prompt
    --links-out .clawcommit/pr-1.md
    --links-include-prompt
`);
}

function parseBoolean(value, fallback) {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }
  const normalized = String(value).trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) {
    return true;
  }
  if (["0", "false", "no", "off"].includes(normalized)) {
    return false;
  }
  throw new Error(`Invalid boolean value: ${value}`);
}

function parseArgs(argv) {
  const args = {
    repo: process.cwd(),
    network: "bscTestnet",
    rpc: "",
    contract: "",
    prompt: "",
    output: "",
    modelVersion: "",
    nonce: "",
    decisionJson: "",
    allowMainnetWrites: false,
    jsonOut: "",
    jsonIncludePrompt: false,
    linksOut: "",
    linksTitle: "ClawCommit Decision Cycle",
    linksIncludePrompt: false,
    linksPromptMaxChars: "1200",
    linksNoRedact: false,
    postGhPr: "",
    ghRepo: "",
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    switch (arg) {
      case "--repo":
        args.repo = path.resolve(argv[++i] || args.repo);
        break;
      case "--network":
        args.network = argv[++i] || args.network;
        break;
      case "--rpc":
        args.rpc = argv[++i] || "";
        break;
      case "--contract":
        args.contract = argv[++i] || "";
        break;
      case "--prompt":
        args.prompt = argv[++i] || "";
        break;
      case "--output":
        args.output = argv[++i] || "";
        break;
      case "--model-version":
        args.modelVersion = argv[++i] || "";
        break;
      case "--nonce":
        args.nonce = argv[++i] || "";
        break;
      case "--decision-json":
        args.decisionJson = path.resolve(argv[++i] || "");
        break;
      case "--allow-mainnet-writes":
        args.allowMainnetWrites = parseBoolean(argv[++i], false);
        break;
      case "--json-out":
        args.jsonOut = argv[++i] || "";
        break;
      case "--json-include-prompt":
        args.jsonIncludePrompt = true;
        break;
      case "--links-out":
        args.linksOut = argv[++i] || "";
        break;
      case "--links-title":
        args.linksTitle = argv[++i] || args.linksTitle;
        break;
      case "--links-include-prompt":
        args.linksIncludePrompt = true;
        break;
      case "--links-prompt-max-chars":
        args.linksPromptMaxChars = argv[++i] || args.linksPromptMaxChars;
        break;
      case "--links-no-redact":
        args.linksNoRedact = true;
        break;
      case "--post-gh-pr":
        args.postGhPr = argv[++i] || "";
        break;
      case "--gh-repo":
        args.ghRepo = argv[++i] || "";
        break;
      case "-h":
      case "--help":
        usage();
        process.exit(0);
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return args;
}

function applyDecisionJson(args) {
  if (!args.decisionJson) {
    return;
  }
  if (!fs.existsSync(args.decisionJson)) {
    throw new Error(`Decision JSON not found: ${args.decisionJson}`);
  }

  const decision = JSON.parse(fs.readFileSync(args.decisionJson, "utf8"));
  args.prompt = decision.prompt || args.prompt;
  args.output = decision.output || args.output;
  args.modelVersion = decision.modelVersion || args.modelVersion;
  args.nonce = decision.nonce || args.nonce;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  applyDecisionJson(args);

  if (!args.contract || !args.prompt || !args.output || !args.modelVersion) {
    throw new Error(
      "Missing required args: --contract and either --decision-json or --prompt/--output/--model-version"
    );
  }

  const script = path.join(args.repo, "skills/operate-clawcommit/scripts/decision_cycle.sh");
  if (!fs.existsSync(script)) {
    throw new Error(`decision_cycle.sh not found: ${script}`);
  }

  const cmd = [
    script,
    "--repo",
    args.repo,
    "--network",
    args.network,
    "--contract",
    args.contract,
    "--prompt",
    args.prompt,
    "--output",
    args.output,
    "--model-version",
    args.modelVersion,
    "--allow-mainnet-writes",
    args.allowMainnetWrites ? "true" : "false",
  ];

  if (args.rpc) {
    cmd.push("--rpc", args.rpc);
  }
  if (args.nonce) {
    cmd.push("--nonce", args.nonce);
  }
  if (args.jsonOut) {
    cmd.push("--json-out", args.jsonOut);
  }
  if (args.jsonIncludePrompt) {
    cmd.push("--json-include-prompt");
  }
  if (args.linksOut) {
    cmd.push("--links-out", args.linksOut);
  }
  if (args.linksTitle) {
    cmd.push("--links-title", args.linksTitle);
  }
  if (args.linksIncludePrompt) {
    cmd.push("--links-include-prompt", "--links-prompt-max-chars", String(args.linksPromptMaxChars));
    if (args.linksNoRedact) {
      cmd.push("--links-no-redact");
    }
  }
  if (args.postGhPr) {
    cmd.push("--post-gh-pr", String(args.postGhPr));
  }
  if (args.ghRepo) {
    cmd.push("--gh-repo", args.ghRepo);
  }

  const result = spawnSync("bash", cmd, { stdio: "inherit" });
  process.exit(typeof result.status === "number" ? result.status : 1);
}

try {
  main();
} catch (error) {
  console.error(`[openclaw-wrapper] ${error.message || error}`);
  process.exit(1);
}
